

module.exports = {"":"Dashboard",
                  "login":"Prosím, přihlaste se",
                  "blog":"Blog",
                  "blog/new":"Nový příspěvek",
                  "blog/edit":"Upravit Příspěvek",
                  "page":"Stránky",
                  "page/new":"Nová stránka",
                  "page/edit":"",
                  "files":"Soubory",
                  "blog/section":"Sekce",
                  "blog/section/new":"Nová Sekce",
                  "blog/section/edit":"",
                  "users" : "Uživatelé",
                  "stats": "Statistiky",
                  "comments": "Komentáře",
                  "users/new": "Nový Uživatel",
                  "users/edit/": "",
                  "menu": "Menu",
                  "menu/new": "Nová Položka Menu",
                  "menu/edit": "",
                  "generate": "Statické soubory",
                  "template": "Šablony",
                  "template/new": "Nová šablona",
                  }
